site_name: Jedaísmo Agnóstico Moderado 
site_description: "Larjam é um guia para o Jedaísmo Agnóstico Moderado, uma filosofia de vida que busca a harmonia entre ciência, espiritualidade e ética."
site_author: "EOM-JAM"
site_version: "1.0.0"
site_url: https://eom-jam.github.io/larjam/
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit

nav:
  - Larjam: index.md
  - Fundamentos:
      - Nomus: fundamentos/nomus.md
      - Emaranhamento: fundamentos/emaranhamento.md
      - eom: fundamentos/eom.md
  - Jam: jam.md
  - Glossário: glossario.md
  - Referências filosóficas: referencias_filosoficas.md
  - Como Contribuir: 
      - Guia de colaboração: Colaboracao.md
      - Código de Conduta: Conduta.md

  - Licença: licenca.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eom-jam/larjam
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: false
  - tables