site_name: Jedaísmo Agnóstico Moderado 
site_description: "Larjam é um guia para o Jedaísmo Agnóstico Moderado, uma filosofia de vida que busca a harmonia entre ciência, espiritualidade e ética."
site_author: "EOM-JAM"
site_url: https://eom-jam.github.io/larjam/
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit

nav:
  - Jam: index.md
  - Larjam: larjam.md
  - Sobre:
    - A religião:
      - Nome: jam/nome.md
      - Agnosticismo: jam/agnosticismo.md
      - Moderação: jam/moderacao.md
  - Fundamentos:
    - Ciencia:
      - Forças: fundamentos/ciencia/forcas.md
      - Modelo padrão: fundamentos/ciencia/modelo_padrao.md
    - Crencas:
      - Força: fundamentos/crencas/forca.md
      - Dinheiro: fundamentos/crencas/dinheiro.md
      - Ato de fé: fundamentos/crencas/atos_de_fe.md
    - Epistemologia:
      - Nomus: fundamentos/epistemologia/nomus.md
      - eom: fundamentos/epistemologia/eom.md
      - Emaranhamento: fundamentos/epistemologia/emaranhamento.md
      - Alinhamento: fundamentos/epistemologia/alinhamento.md
  - Composição:
    - Referências: 
      - Filosofia: construcao/referencias_filosoficas.md
      - Glossário: construcao/glossario.md
    - Como Contribuir: 
      - Manifesto: construcao/manifesto.md
      - Guia de colaboração: construcao/colaboracao.md
      - Código de Conduta: construcao/conduta.md
      - Licença: construcao/licenca.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eom-jam/larjam
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: false
  - tables